from .point import Point
from .line import Line
from .shape import Shape
from .rectangle import Rectangle
from .triangle import Triangle
from .equilateral import Equilateral
from .isosceles import Isosceles
from .scalene import Scalene
from .trirectangle import TriRectangle